# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://machariavck.github.io"

[_.globalMeta]
title = "machariavck"
description = "security research"
keywords = ["security", "cybersec", "research"]

[_.blogMeta]
title = "blog"
description = "The blog"

[_.aboutMeta]
title = "about"
description = "About author"

[_.notFoundMeta]
title = "404"
description = "Not Found"

[_.personal]
name = "machariavck"
xProfile = "https://x.com/machariavck"

[_.texts]
articlesName = "Articles"
viewAll = "View All"
noArticles = "No Articles Found."

[_.menu]
home = "/"
blog = "/blog"
about = "/about"
